### ISSUE TITLE
Error in inflating layout due to adview in main.layout

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#102]
The app is crashing in tablet due to incorrect xmls:ads in main.xml(layout) 

**Expected Behaviour**
  xmlns:ads="http://schemas.android.com/apk/lib/com.google.ads" 
should be replaced with    
 xmlns:app="http://schemas.android.com/apk/res-auto".
  **or**
Comment adviews in main layout (large,small,x-large).

**Steps to reproduce it**

Try to run this app in the tablet (large- screen devices). Open mail.xm(layout-large,small,land,x-large).

**LogCat for the issue**

java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.mbm.phimp.me/vn.mbm.phimp.me.PhimpMe}: android.view.InflateException: Binary **XML file line #47: Error inflating class com.google.ads.AdView
  at** android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2260)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325)
  at android.app.ActivityThread.access$800(ActivityThread.java:145)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:5266)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
  at dalvik.system.NativeStart.main(Native Method)
  Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class com.google.ads.AdView
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:711)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
  at vn.mbm.phimp.me.PhimpMe.onCreate(PhimpMe.java:216)
  at android.app.Activity.performCreate(Activity.java:5277)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325) 
  at android.app.ActivityThread.access$800(ActivityThread.java:145) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:145) 
  at android.app.ActivityThread.main(ActivityThread.java:5266) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:515) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) 
  at dalvik.system.NativeStart.main(Native Method) 
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ads.AdView" on path: DexPathList[[zip file "/data/app/vn.mbm.phimp.me-2.apk", zip file "/system/priv-app/AmazonPlatform-release.apk", zip file "/system/priv-app/DeviceClientPlatformContractsFramework.apk", zip file "/system/priv-app/DeviceSoftwareOTAContracts.apk", zip file "/system/priv-app/MetricsApi-2066310.apk", zip file "/system/priv-app/RemoteSettingsInternalSDK.apk", zip file "/system/priv-app/amazon.jackson-19.apk", zip file "/system/priv-app/com.amazon.communication.apk", zip file "/system/priv-app/com.amazon.dp.logger.apk"],nativeLibraryDirectories=[/data/app-lib/vn.mbm.phimp.me-2, /vendor/lib, /system/lib]]
  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
  at android.view.LayoutInflater.createView(LayoutInflater.java:563)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
  at vn.mbm.phimp.me.PhimpMe.onCreate(PhimpMe.java:216) 
  at android.app.Activity.performCreate(Activity.java:5277) 

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
Or should I comment adview because we are not using right now?

**Comment by pa1pal** [comment]
Yes @mohitmanuja  We are not using it now. You can remove the ads part.

**Comment by mohitmanuja** [comment]
@pa1pal Okay sure. 
I will remove that.
