### ISSUE TITLE
App Crashes by Clicking on Accounts Button

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1115]
**Actual Behaviour**

The App Crashes on Clicking Accounts Buttns

**Expected Behaviour**

The App should work fine

**Steps to reproduce it**

Open Phimpme and click on Accounts Button

**LogCat for the issue**

09-12 22:18:00.212 427-427/org.fossasia.phimpme D/AndroidRuntime: Shutting down VM
09-12 22:18:00.213 427-427/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: org.fossasia.phimpme, PID: 427
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dropbox/client2/session/AppKeyPair;
                                                                      at org.fossasia.phimpme.accounts.AccountActivity.setupDropBox(AccountActivity.java:159)
                                                                      at org.fossasia.phimpme.accounts.AccountActivity.onCreate(AccountActivity.java:153)
                                                                      at android.app.Activity.performCreate(Activity.java:5953)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dropbox.client2.session.AppKeyPair" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-2/base.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_dependencies_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-2/lib/arm, /vendor/lib, /system/lib]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                      at org.fossasia.phimpme.accounts.AccountActivity.setupDropBox(AccountActivity.java:159) 
                                                                      at org.fossasia.phimpme.accounts.AccountActivity.onCreate(AccountActivity.java:153) 
                                                                      at android.app.Activity.performCreate(Activity.java:5953) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388) 
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:148) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5312) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
                                                                  	Suppressed: java.lang.ClassNotFoundException: com.dropbox.client2.session.AppKeyPair
                                                                      at java.lang.Class.classForName(Native Method)
                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                      		... 16 more
                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Screenshots of the issue**

![screenshot_2017-09-12-22-18-34](https://user-images.githubusercontent.com/20026440/30338356-0927456e-9809-11e7-9cbe-2921fe1456e1.png)

**Would you like to work on the issue?**

YES

**Comment by codedsun** [comment]
@mohitmanuja kindly chck the issue.

**Comment by codedsun** [comment]
@mohitmanuja Kindly Review this issue.

**Comment by codedsun** [comment]
@mohitmanuja  @anantprsd5 @pa1pal kindly tell me further what shall be done for this issue.

**Comment by codedsun** [comment]
@mohitmanuja need help for this issue.

**Comment by codedsun** [comment]
@anantprsd5 need reviews so that I can proceed further

**Comment by anantprsd5** [comment]
@codesun Is the app crashing on clicking the accounts button or while trying to upload to Dropbox?

**Comment by codedsun** [comment]
@anantprsd5 yes

**Comment by yashLadha** [comment]
I would like to send a PR for the Issue. @vinaysajjanapu

**Comment by codedsun** [comment]
we have been using API v1 for dropbox which has been depreciated,we should move to APIv2.!
Kindly review it so that I can proceed @anantprsd5 @vinaysajjanapu @mohitmanuja

**Comment by batbrain7** [comment]
@vinaysajjanapu I would like to work on this issue since it has been a long time and no work has been done yet

**Comment by codedsun** [comment]
@batbrain7 PR has been send regarding this, its waiting to be merged as soon as they are online
