### ISSUE TITLE
App Crashes On Clicking the Filter Icon

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1120]
**Actual Behaviour**

The App Crashes while Clicking on the filter icon while using the front camera

**Expected Behaviour**
It should work fine and should apply filters

**Steps to reproduce it**
Open the app ,toggle to the front camera ,Click on the filter icon on the left hand side.

**LogCat for the issue**

09-12 23:39:11.337 18526-18526/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 18526
                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                          at org.fossasia.phimpme.opencamera.Preview.Preview$6.onClick(Preview.java:1396)
                                                                          at android.view.View.performClick(View.java:4761)
                                                                          at android.view.View$PerformClick.run(View.java:19767)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Screenshots of the issue**

**Would you like to work on the issue?**

YES!

**Comment by sridharjajoo** [comment]
@codedsun Which android version are you using ?

**Comment by codedsun** [comment]
@sridharjajoo Android 5.0.2,API21

**Comment by sridharjajoo** [comment]
I tried it on my android device but it is working fine . I am using Android 5.1.1 API 22

**Comment by codedsun** [comment]
@sridharjajoo  I am using MotoE (2nd generation) device with android 5.0.2..It still crashes

**Comment by Siddharth-Singhs** [comment]
it crashes when we try to change the filter continuously.

**Comment by codedsun** [comment]
@Siddharth-Singhs  But for the app on my phone it's still crashing on clicking the filter icon? so is this an issue or not?

**Comment by NamanRawat1** [comment]
Use try-catch in part of the program which shows runtime error.It fixes your problem. @codedsun

**Comment by codedsun** [comment]
:P @NamanRawat1  I think it will be problem for all the people using the same code !though it will work on my pc  if I use the try-catch

**Comment by NamanRawat1** [comment]
You can make a PR after testing. @codedsun

**Comment by codedsun** [comment]
@NamanRawat1  let the mentors comment so that I can test and fix the issue .

**Comment by codedsun** [comment]
@mohitmanuja kindly review this too..bug for moto phones

**Comment by mohitmanuja** [comment]
Okay. Add null check in list and proceed.

**Comment by codedsun** [comment]
@mohitmanuja shall I go on with try/catch because if statement chck will cause further crash as colorEffect list is accesed later within same block?

**Comment by mohitmanuja** [comment]
Ok.

**Comment by codedsun** [comment]
what should be shown while catching the exception? any log or something else !

**Comment by codedsun** [comment]
what should be shown while catching the exception? any log or something else ! @mohitmanuja

**Comment by mohitmanuja** [comment]
Toast msg with log will be good.

**Comment by codedsun** [comment]
Can u guide me the content to be shown ..sorry for that but I m a noob

**Comment by mohitmanuja** [comment]
Yes sure. You can display message like "Your device does not support any filters."

**Comment by codedsun** [comment]
@mohitmanuja done fixed the issue ! It would be great if you guide me regarding submitting the PR as I am  a newbie.
