### ISSUE TITLE
App Crashes While Integrating With Dropbox

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1125]
**Actual Behaviour**
App is Crashing When I try to setup Dropbox Account

**Expected Behaviour**

It should work fine

**Steps to reproduce it**
Open Accounts and Click on Dropbox Account

**LogCat for the issue**

FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 15974
                                                                      java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.client2.android.AuthActivity with the scheme: db-DROPBOX_APP_KEY
                                                                          at com.dropbox.client2.android.AuthActivity.checkAppBeforeAuth(AuthActivity.java:265)
                                                                          at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:174)
                                                                          at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:143)
                                                                          at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:116)
                                                                          at org.fossasia.phimpme.accounts.AccountActivity.signInDropbox(AccountActivity.java:386)
                                                                          at org.fossasia.phimpme.accounts.AccountActivity.onItemClick(AccountActivity.java:277)
                                                                          at org.fossasia.phimpme.base.RecyclerItemClickListner$GestureListener.onSingleTapUp(RecyclerItemClickListner.java:73)
                                                                          at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
                                                                          at org.fossasia.phimpme.base.RecyclerItemClickListner.onInterceptTouchEvent(RecyclerItemClickListner.java:31)
                                                                          at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2658)
                                                                          at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2786)
                                                                          at android.view.View.dispatchTouchEvent(View.java:9419)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2305)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2319)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
                                                                          at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1772)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2846)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2414)
                                                                          at android.view.View.dispatchPointerEvent(View.java:9650)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4753)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4611)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4169)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4135)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4281)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4143)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4338)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                      	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4

**Screenshots of the issue**

**Would you like to work on the issue?**

YES

**Comment by codedsun** [comment]
@mohitmanuja Kindly review.

**Comment by mohitmanuja** [comment]
It is not an error. You have to enter api key in manifest file. 

Search dropbox in manifest.

**Comment by codedsun** [comment]
Okay got it! shall I close this issue?

**Comment by mohitmanuja** [comment]
Yes.

**Comment by codedsun** [comment]
Kindly check other issues too I have tagged u in.
Thanks
Closing .
