### ISSUE TITLE
Getting error when using accounts

### ISSUE THREAD

**Issue by yashLadha** [fossasia/phimpme-android#1159]
**LogCat for the issue**

```
FATAL EXCEPTION: main
                                                                    Process: org.fossasia.phimpme, PID: 4167
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dropbox/client2/session/AppKeyPair;
                                                                        at org.fossasia.phimpme.accounts.AccountActivity.setupDropBox(AccountActivity.java:159)
                                                                        at org.fossasia.phimpme.accounts.AccountActivity.onCreate(AccountActivity.java:153)
                                                                        at android.app.Activity.performCreate(Activity.java:5937)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dropbox.client2.session.AppKeyPair" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/x86, /vendor/lib, /system/lib]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                        at org.fossasia.phimpme.accounts.AccountActivity.setupDropBox(AccountActivity.java:159) 
                                                                        at org.fossasia.phimpme.accounts.AccountActivity.onCreate(AccountActivity.java:153) 
                                                                        at android.app.Activity.performCreate(Activity.java:5937) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                                                                    	Suppressed: java.lang.ClassNotFoundException: com.dropbox.client2.session.AppKeyPair
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                        		... 16 more
                                                                     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

Unable to get keys for dropbox account

Actually: It is not for the key for dropbox and as on some devices may be drop box is not installed so it is not able to configure those keys and crashing the whole app. What we can do instead is to put that in try catch and log those errors and avoid crashing the app. I can send a PR for the same issue.

**Comment by vinaysajjanapu** [comment]
@anantprsd5

**Comment by vinaysajjanapu** [comment]
#1115 
@yashLadha you can work on that issue if you wish.
