### ISSUE TITLE
Bug in all slider fragment related edit modes

### ISSUE THREAD

**Issue by nb2998** [fossasia/phimpme-android#1245]
**Actual Behaviour**

The screen goes blank in slider fragment related edit mode (Enhance, Filters modes) on changing seekBar progress after pressing undo and removing the previous edits. 
Also, on pressing undo, the preview of filter modes does not change.

**Expected Behaviour**

The screen should not go blank and the changes made to the progressBar should be visible. Also, the preview of filter modes should be visible

**Steps to reproduce it**

Choose any filter and apply the changes. Now choose any filter again. Click on undo. Change the seekbar progress.

**LogCat for the issue**

`09-30 23:57:40.847 32268-32268/? E/FirebaseApp: Firebase API initialization failure.
                                                java.lang.reflect.InvocationTargetException
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1734)
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5921)
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:5470)
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5409)
                                                    at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.app.ActivityThread.main(ActivityThread.java:6195)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzapn;
                                                    at com.google.android.gms.internal.zzbku.<clinit>(Unknown Source)
                                                    at com.google.android.gms.internal.zzbku.initialize(Unknown Source)
                                                    at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1759) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1734) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5921) 
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:5470) 
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5409) 
                                                    at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:154) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:6195) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzapn" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-1/base.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-1/lib/arm, /data/app/org.fossasia.phimpme-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                    at com.google.android.gms.internal.zzbku.<clinit>(Unknown Source) 
                                                    at com.google.android.gms.internal.zzbku.initialize(Unknown Source) 
                                                    at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1759) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1734) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5921) 
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:5470) 
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5409) 
                                                    at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:154) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:6195) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
`

**Screenshots of the issue**

![20170930_185947](https://user-images.githubusercontent.com/25134501/31048199-32a7ceaa-a636-11e7-9f7a-58c7b0047040.gif)

**Would you like to work on the issue?**

Yes @anantprsd5 @vinaysajjanapu @mohitmanuja

**Comment by codedsun** [comment]
I see no issues currently in the app, kindly close this issue.
