### ISSUE TITLE
App stop working when pressing "Use as" in selected picture

### ISSUE THREAD

**Issue by ashley8jain** [fossasia/phimpme-android#1550]
**Actual Behaviour**

App stop working after pressing "Use as" in selected picture

**LogCat for the issue**
```
12-26 19:27:54.535 18495-18495/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 18495
                                                                      android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/Camera/IMG_20171019_163957.jpg exposed beyond app through Intent.getData()
                                                                          at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
                                                                          at android.net.Uri.checkFileUriExposed(Uri.java:2348)
                                                                          at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
                                                                          at android.content.Intent.prepareToLeaveProcess(Intent.java:9856)
                                                                          at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:4487)
                                                                          at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:4445)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                          at android.app.Activity.startActivity(Activity.java:4806)
                                                                          at android.app.Activity.startActivity(Activity.java:4774)
                                                                          at org.fossasia.phimpme.gallery.activities.SingleMediaActivity.onOptionsItemSelected(SingleMediaActivity.java:732)
                                                                          at android.app.Activity.onMenuItemSelected(Activity.java:3450)
                                                                          at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                                          at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                                          at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                          at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                          at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                                          at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                                          at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                          at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                          at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                                                                          at android.widget.AdapterView.performItemClick(AdapterView.java:318)
                                                                          at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
                                                                          at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
                                                                          at android.widget.AbsListView$3.run(AbsListView.java:4042)
                                                                          at android.os.Handler.handleCallback(Handler.java:790)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
**Screenshots of the issue**

![screenshot_20171226-192628](https://user-images.githubusercontent.com/16614355/34358227-e382ce1a-ea73-11e7-9c36-b3a2eb1946a3.png)

**Would you like to work on the issue?**

Yes

**Comment by sauravvishal8797** [comment]
@ashley8jain Use me feature is working just fine for me, can you please check again and confirm the issue.

**Comment by ashley8jain** [comment]
@sauravvishal8797 It is not working in SDK version 24 or above.
https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by ashley8jain** [comment]
It also fixed the sharing to media error **android.os.FileUriExposedException**.
@anantprsd5 @mohitmanuja Please review this.
