### ISSUE TITLE
Upload History App Crash

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1564]
**Actual Behaviour**

The app is crashing on navigating to the upload history drawer menu

**Expected Behaviour**

It should not crash.

**Steps to reproduce it**

Go to upload history from drawer menu.

**Logs**
01-09 01:12:12.030 8623-8623/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.fossasia.phimpme, PID: 8623
                                                                    android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                        at android.content.res.Resources.getValue(Resources.java:1561)
                                                                        at android.content.res.Resources.getColor(Resources.java:1112)
                                                                        at android.content.Context.getColor(Context.java:446)
                                                                        at android.support.v4.content.ContextCompatApi23.getColor(ContextCompatApi23.java:32)
                                                                        at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:432)
                                                                        at org.fossasia.phimpme.uploadhistory.UploadHistoryAdapter.onBindViewHolder(UploadHistoryAdapter.java:93)
                                                                        at org.fossasia.phimpme.uploadhistory.UploadHistoryAdapter.onBindViewHolder(UploadHistoryAdapter.java:38)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1190)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2740)
                                                                        at android.view.View.layout(View.java:16967)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5585)
                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2562)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2265)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6718)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                    	at android.view.Choreographer.doCallbacks(Choreogr

**Would you like to work on the issue?**

Yes!

**Comment by sauravvishal8797** [comment]
@codedsun Its working fine for me, can you please recheck and confirm the issue.

**Comment by sridharjajoo** [comment]
@codedsun Yeah , it is working fine.Can you please upload the logcat.

**Comment by sridharjajoo** [comment]
@codedsun I think you can close the issue.

**Comment by codedsun** [comment]
I am still getting the issue @sridharjajoo @sauravvishal8797 ! check the description, added the logcat

**Comment by codedsun** [comment]
Okay, I debugged it. The problem was occurring in my PC because I have shared the image on google drive while integrating Google Drive hence the PR is not merged yet, so it was not able to find the resource.

Closing the issue!
