### ISSUE TITLE
App crashes on clicking the camera button

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1651]
**Actual Behaviour**
The app is crashing on taking pictures.

**Expected Behaviour**

The should not crash on taking pictures.

**LogCat for the issue**

01-12 21:58:24.963 2926-5244/? E/Sensors: handleToDriver handle(3)
01-12 21:58:24.963 2926-5244/? E/Sensors: new setDelay handle(3),ns(10000000)m, error(0), index(4)
01-12 21:58:25.053 26043-27049/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: Thread-13
                                                                      Process: org.fossasia.phimpme, PID: 26043
                                                                      java.lang.NumberFormatException: For input string: ""
                                                                          at java.lang.Integer.parseInt(Integer.java:533)
                                                                          at java.lang.Integer.parseInt(Integer.java:556)
                                                                          at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveSingleImageNow(ImageSaver.java:1431)
                                                                          at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveImageNow(ImageSaver.java:700)
                                                                          at org.fossasia.phimpme.opencamera.Camera.ImageSaver.run(ImageSaver.java:203)

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
No it isn't in my phone

**Comment by raj10071997** [comment]
@sridharjajoo  at first the app wasn't crashing in my phone too. But then I set a password and deleted an image, removed the password and then reset all the settings. After that when I wanted to click a photo the app was crashing. So I looked at the logcat and I found the above error as shown by the logcat.

**Comment by codedsun** [comment]
@raj10071997 Please mention the exact steps to reproduce the issue.

**Comment by raj10071997** [comment]
@codedsun  just select the Reset Settings option from settings and try to take click a photo from the camera option , the app will stop.

**Comment by codedsun** [comment]
@sridharjajoo Please confirm. @raj10071997 I think you are good to solve this.

**Comment by sridharjajoo** [comment]
@raj10071997 Go ahead!
