### ISSUE TITLE
Google Drive sign in causes the app to crash

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1657]
**Actual Behaviour**

The app stops when trying to sign to google drive.

**Expected Behaviour**

The app should not crash when trying to sign in to google drive.

**LogCat for the issue**

01-14 17:27:10.516 1984-2022/? E/GED: Failed to execute ioctl 3222824709, BridgeID(5), err(-1)
01-14 17:27:10.631 24296-24337/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                      **Process: org.fossasia.phimpme, PID: 24296
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       _Caused by: java.lang.RuntimeException: A valid CloudRail license key is required. You can get one for free at https://developers.cloudrail.com
                                                                          at com.cloudrail.si.CloudRail.validateKey(CloudRail.java:34)
                                                                          at com.cloudrail.si.services.GoogleDrive.login(GoogleDrive.java:1799)
                                                                          _at org.fossasia.phimpme.accounts.CloudRailServices$DriveLogin.doInBackground(CloudRailServices.java:125)
                                                                          at org.fossasia.phimpme.accounts.CloudRailServices$DriveLogin.doInBackground(CloudRailServices.java:114)__
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:761)** 
01-14 17:27:10.726 2572-3962/? E/GED: failed to open /proc/ged
01-14 17:27:10.726 2572-3962/? E/GED: Failed to open ged device
01-14 17:27:11.328 1984-1987/? E/GED: Failed to execute ioctl 3222824709, BridgeID(5), err(-1)
01-14 17:27:11.328 1984-1987/? E/GasService: Error on query GED info, err=1
01-14 17:27:11.801 2160-2508/? E/VT_ERROR: [SRV] [VT THREAD] [VT_Bind] des = volte_imsvt1 Fail to connect . retry count: 10063
01-14 17:27:12.296 2332-2402/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1893) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8 sim:1
01-14 17:27:12.328 1984-1987/? E/GED: Failed to execute ioctl 3222824709, BridgeID(5), err(-1)
01-14 17:27:12.328 1984-1987/? E/GasService: Error on query GED info, err=1
01-14 17:27:13.329 1984-1987/? E/GED: Failed to execute ioctl 3222824709, BridgeID(5), err(-1)
01-14 17:27:13.329 1984-1987/? E/GasService: Error on query GED info, err=1

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@raj10071997 This states that you don't have cloudrail account setup, this means you have to go to cloudrail and get it setup.

**Comment by raj10071997** [comment]
@codedsun  do I have to enter the cloudrail and google drive API keys only for the above issue to be resolved? And in issue #1658 you mentioned the 3rd point that - "Add the details of how to enable various services within their app" . Can you please describe this point here so that I can better understand the issue?

**Comment by codedsun** [comment]
go to the website and u will know 👍 and issue updated!

**Comment by codedsun** [comment]
@raj10071997 I think, we can close the issue.

**Comment by raj10071997** [comment]
@codedsun  sure.
