### ISSUE TITLE
App crashes on sending photos

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1741]
**Actual Behaviour**
I have downloaded an image from chrome and when I try to send it through the app to messenger, the app crashes. 

**Expected Behaviour**

The app should not crash. Seeing the logcat, it seems that the mime type is null for that image.

**LogCat for the issue**

01-25 19:07:18.501 1984-2022/? E/GED: Failed to execute ioctl 3222824709, BridgeID(5), err(-1)
01-25 19:07:18.716 13174-13174/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 13174
                                                                      java.lang.NullPointerException: Must provide mimeType
                                                                          at com.facebook.messenger.ShareToMessengerParams.<init>(ShareToMessengerParams.java:103)
                                                                          at com.facebook.messenger.ShareToMessengerParamsBuilder.build(ShareToMessengerParamsBuilder.java:120)
                                                                          at org.fossasia.phimpme.share.SharingActivity.shareToMessenger(SharingActivity.java:1080)
                                                                          at org.fossasia.phimpme.share.SharingActivity.access$1600(SharingActivity.java:165)
                                                                          at org.fossasia.phimpme.share.SharingActivity$2.onClick(SharingActivity.java:381)
                                                                          at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:203)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6343)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
01-25 19:07:18.809 2572-3962/? E/GED: failed to open /proc/ged
01-25 19:07:18.809 2572-3962/? E/GED: Failed to open ged device

**Gif of the issue**
![download](https://user-images.githubusercontent.com/24502136/35391352-658cea60-0204-11e8-9ba3-8c76390b016c.gif)

**Would you like to work on the issue?**
Yes.

**Comment by ashley8jain** [comment]
@raj10071997 u r still working on this issue?. Please let me know

**Comment by raj10071997** [comment]
@ashley8jain yes I am still working on this. Presently I am little busy and will be sending a PR regarding this issue soon.

**Comment by raj10071997** [comment]
@ashley8jain if you want to work, you can work on issue #1635. I have been trying to find a solution but couldn't. I have also mentioned the part of the code which is causing the issue.
