### ISSUE TITLE
App Crash On Redmi 2Prime Android 5.1.1

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/phimpme-android#1759]
**Actual Behaviour**

App Crash on open /not working currently

**Expected Behaviour**

App Should not Crash

**Steps to reproduce it**

launch App in Redmi 2 Prime 

**LogCat for the issue**

` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 19586
                                                                      java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-2/base.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_dependencies_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-2/lib/arm, /vendor/lib, /system/lib]]
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:5035)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4627)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5296)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-2/base.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_dependencies_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_0_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_1_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_2_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_3_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_4_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_5_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_6_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_7_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_8_apk.apk", zip file "/data/app/org.fossasia.phimpme-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-2/lib/arm, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:5020)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4627) 
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567) 
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:154) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5296) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 13 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Would you like to work on the issue?**
yes

**Comment by jindalAnuj** [comment]
@isuruAb please see the above issue
