### ISSUE TITLE
App is crashing when setting the value of Burst in Camera Settings to "Unlimited"

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1835]
**Actual Behaviour**
When you set the value of Burst to "Unlimited" and then try to take photos through camera, the app is crashing.

**Expected Behaviour**

The app shouldn't crash.

**Steps to reproduce it**

Open settings, then Camera Settings. Now click on Burst option and set the value to unlimited.

**LogCat for the issue**

02-11 11:19:11.095 4867-4867/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.fossasia.phimpme, PID: 4867
                                                                    java.lang.NumberFormatException: For input string: "unlimited"
                                                                        at java.lang.Integer.parseInt(Integer.java:521)
                                                                        at java.lang.Integer.parseInt(Integer.java:556)
                                                                        at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveSingleImageNow(ImageSaver.java:1438)
                                                                        at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveImageNow(ImageSaver.java:700)
                                                                        at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveImage(ImageSaver.java:387)
                                                                        at org.fossasia.phimpme.opencamera.Camera.ImageSaver.saveImageJpeg(ImageSaver.java:264)
                                                                        at org.fossasia.phimpme.opencamera.Camera.MyApplicationInterface.saveImage(MyApplicationInterface.java:1188)
                                                                        at org.fossasia.phimpme.opencamera.Camera.MyApplicationInterface.onPictureTaken(MyApplicationInterface.java:1220)
                                                                        at org.fossasia.phimpme.opencamera.Preview.Preview$11.onPictureTaken(Preview.java:3395)
                                                                        at org.fossasia.phimpme.opencamera.CameraController.CameraController1$4.onPictureTaken(CameraController1.java:1464)
                                                                        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1316)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                        at android.os.Looper.loop(Looper.java:203)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6343)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Would you like to work on the issue?**

Yes.

**Comment by Pravesh-Jamgade** [comment]
hello,im beginner here.Im getting problem with building project because of deprecated libraries and others.could you help me with that? its been a while im trying but not getting any further.

**Comment by sridharjajoo** [comment]
The issue has already been made and a pr has been sent for the same...https://github.com/fossasia/phimpme-android/pull/1792
Kindly close this issue

**Comment by raj10071997** [comment]
@Pravesh-Jamgade If you are facing any issue and you need help with that, you can post your query in the gitter channel. I and others will be helping you there. Please post some screenshots or give all the details you can about your query, so that others can better understand your problem. :smile: 

@sridharjajoo  Sure, I am closing this issue.
