### ISSUE TITLE
App crashes on toggle filter long press for no effects

### ISSUE THREAD

**Issue by mayank8318** [fossasia/phimpme-android#1859]
**Actual Behaviour**

The app crashes on long pressing the toggle filter icon when the device doesn't support color filters.

**Expected Behaviour**

The app shouldn't crash and work as normal.

**Steps to reproduce it**

Long press the toggle filter icon.
App will crash if your phone doesn't support filters.

**LogCat for the issue**

02-16 23:01:47.310 9901-9901/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.fossasia.phimpme, PID: 9901
                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                                        at org.fossasia.phimpme.opencamera.Preview.Preview$7.onLongClick(Preview.java:1424)
                                                                        at android.view.View.performLongClickInternal(View.java:6338)
                                                                        at android.view.View.performLongClick(View.java:6296)
                                                                        at android.view.View.performLongClick(View.java:6314)
                                                                        at android.view.View$CheckForLongPress.run(View.java:23717)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Would you like to work on the issue?**

Yes

**Comment by Navd15** [comment]
hey @mayank8318  u still workig on this issue...??
.

**Comment by mayank8318** [comment]
@Navd15 Yes
