### ISSUE TITLE
App is crashing on tablets whenever using large,small,x-large layouts

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/phimpme-android#224]
**Actual Behaviour**

App is crashing in tablets because in other xmls like large,xtra large, small the proper views in not included. Null pointer exceptions.

**Expected Behaviour**

App should run properly in tablets.

![screenshot_2017-03-22-16-14-08](https://cloud.githubusercontent.com/assets/9361754/24194110/c4ba66c6-0f1a-11e7-8458-a6d22f4ac4ec.png)

**Steps to reproduce it**

Try to open app on tablets.

**LogCat for the issue**

FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 29825
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.mbm.phimp.me/vn.mbm.phimp.me.PhimpMe}: java.lang.NullPointerException
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2260)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5266)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.NullPointerException
                                                                     at vn.mbm.phimp.me.PhimpMe.onCreate(PhimpMe.java:579)
                                                                     at android.app.Activity.performCreate(Activity.java:5277)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:145) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5266) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 

**Would you like to work on the issue?**

Yes. Please let me know. I solved the errors and want to send PR.

**Comment by mohitmanuja** [comment]
@Abhi2424shek @pa1pal  Please have a look.

**Comment by Abhi2424shek** [comment]
Sure pls go on.

**Comment by mohitmanuja** [comment]
@Abhi2424shek I am creating PR and It is showing 7 commits which are already merged with phimpme. How can I include only specific last commit in PR.  or should I send all commit. On comparision with phimpme development branch it is showing recent changes which is right but showing last 7 commit. So should I send PR with 7 commits or how to include only last commit in PR.

Please help me out.

**Comment by Abhi2424shek** [comment]
You need to rebase or send them, I will squash and merge but besure of a new development process, it's in contributing.md file (before making a pr - 5) pls see it too. @mohitmanuja

**Comment by mohitmanuja** [comment]
@Abhi2424shek Yeah Sure, Thanks for suggestion.
