### ISSUE TITLE
 Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.fossasia.phimpme.editor.filter.PhotoProcessing.nativeApplyFilter(int, int, long, long)

### ISSUE THREAD

**Issue by bhavesh-srashtasoft** [fossasia/phimpme-android#2375]
**Actual Behaviour**

Application is running properly but after clicking on Edit app crashed. 

 **Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.fossasia.phimpme.editor.filter.PhotoProcessing.nativeApplyFilter(int, int, long, long)**

(tried Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_nativeApplyFilter and Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_nativeApplyFilter__IIJJ)

 **at org.fossasia.phimpme.editor.filter.PhotoProcessing.nativeApplyFilter(Native Method)
        at org.fossasia.phimpme.editor.filter.PhotoProcessing.processImage(PhotoProcessing.java:25)**
        
at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:153)
        at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:143)

**Expected Behaviour**

User can edit the image properly, it might be setup issue but we need to resolve this. 

**Steps to reproduce it**

1. Open Application
2. Select image from gallery
3. Click on Edit and app will be crashed.

**LogCat for the issue**

  --------- beginning of crash
2019-01-11 19:12:36.987 9924-10144/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
    Process: org.fossasia.phimpme, PID: 9924
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.fossasia.phimpme.editor.filter.PhotoProcessing.nativeApplyFilter(int, int, long, long) (tried Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_nativeApplyFilter and Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_nativeApplyFilter__IIJJ)
        at org.fossasia.phimpme.editor.filter.PhotoProcessing.nativeApplyFilter(Native Method)
        at org.fossasia.phimpme.editor.filter.PhotoProcessing.processImage(PhotoProcessing.java:25)
        at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:153)
        at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:143)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Yes I want to resolve this issue.

**Comment by yashk2000** [comment]
@bhavesh-srashtasoft Can you please describe the issue in more detail? I am not able to reproduce it on my device. On my device, the app isn't crashing on editing images.

Also, this isn't the proper way to open an issue. Please follow the proper guidelines.

**Comment by bhavesh-srashtasoft** [comment]
2019-01-12 13:23:44.321 589-641/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-01-12 13:23:44.324 1581-3127/? E/ActivityTrigger: activityStartTrigger: not whiteListedorg.fossasia.phimpme/org.fossasia.phimpme.editor.EditImageActivity/8
2019-01-12 13:23:44.325 1581-3127/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.fossasia.phimpme/org.fossasia.phimpme.editor.EditImageActivity/8
2019-01-12 13:23:44.359 1581-3127/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.fossasia.phimpme/org.fossasia.phimpme.editor.EditImageActivity/8
2019-01-12 13:23:44.962 31068-32250/org.fossasia.phimpme E/zygote: No implementation found for java.lang.String org.fossasia.phimpme.editor.filter.PhotoProcessing.stringFromJNI() (tried Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_stringFromJNI and Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_stringFromJNI__)
    
    --------- beginning of crash
2019-01-12 13:23:44.966 31068-32250/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
    Process: org.fossasia.phimpme, PID: 31068
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String org.fossasia.phimpme.editor.filter.PhotoProcessing.stringFromJNI() (tried Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_stringFromJNI and Java_org_fossasia_phimpme_editor_filter_PhotoProcessing_stringFromJNI__)
        at org.fossasia.phimpme.editor.filter.PhotoProcessing.stringFromJNI(Native Method)
        at org.fossasia.phimpme.editor.filter.PhotoProcessing.processImage(PhotoProcessing.java:26)
        at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:153)
        at org.fossasia.phimpme.editor.fragment.RecyclerMenuFragment$GetFilterThumbsTask.doInBackground(RecyclerMenuFragment.java:143)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
    
    
    --------- beginning of system
2019-01-12 13:23:45.024 1581-3127/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.fossasia.phimpme/org.fossasia.phimpme.gallery.activities.SingleMediaActivity/8
2019-01-12 13:23:45.024 589-641/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-01-12 13:23:45.279 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.279 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.279 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.279 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.296 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.296 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.296 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.296 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.312 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.312 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.312 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.312 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.329 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.329 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.329 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.329 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.345 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.345 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.346 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.346 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!
2019-01-12 13:23:45.362 573-706/? E/SDM: scalar::adjustSourceCrop: Source crop exceeds source image size: Crop(x,y,w,h)=(0,0,720,1440) Src(x,w)=(0,0)
2019-01-12 13:23:45.362 573-706/? E/SDM: ScalarConfig::ApplyScale: Scalar library failed to configure scale data!


This is My Full Error Check it

**Comment by yashk2000** [comment]
@bhavesh-srashtasoft can you please tell me how to reproduce the error in more detail? This error is not showing up on my device.

**Comment by bhavesh-srashtasoft** [comment]
Application is running properly but after clicking on Edit app crashed.

**Comment by yashk2000** [comment]
Upload a gif.

Also have you built the app correctly? This is the first time I've heard of such an error.

**Comment by bhavesh-srashtasoft** [comment]
Please check this video which i sent

[https://drive.google.com/file/d/1IX0lBpu-p9mvtAs0zAkspDF6kWGMCqt2/view?usp=sharing](url)

**Comment by bhavesh-srashtasoft** [comment]
Hii @yashk2000 

Any Update ??

**Comment by bhavesh-srashtasoft** [comment]
Hello
Can you also tell How to generate so files in perticuler folders ?

**Comment by yashk2000** [comment]
@bhavesh-srashtasoft I saw the video. Did you make any changes to the files in the app? And did you follow all the instructions while building the app properly? If you did it properly and it's still not working, then try to clone the repository and build the app from scratch again.

**Comment by bhavesh-srashtasoft** [comment]
@yashk2000  I have tried 4-5 times from scratch but every time i was stopped t this situation.
i didn't do any change in code but still getting this error everytime

**Comment by yashk2000** [comment]
@bhavesh-srashtasoft I don't know what is causing the error then. You can join the gitter channel of phimpme and ask your questions there so that you can take help from the mentors of the project.

**Comment by bhavesh-srashtasoft** [comment]
@yashk2000  How can i join the gitter channel of phimpme ?

**Comment by yashk2000** [comment]
Here is the link: [https://gitter.im/fossasia/phimpme](https://gitter.im/fossasia/phimpme)

**Comment by bhavesh-srashtasoft** [comment]
ok i will write my issue there

**Comment by bhavesh-srashtasoft** [comment]
i think the error is getting because so files not fetching properly but i was try to many times help me to resolve this
