### ISSUE TITLE
App getting crashed on pressing more button in gallery page

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#260]
**Actual Behaviour**

App is getting crashed on pressing more button in gallery page when "show local photos" is not checked in settings page

**Expected Behaviour**

Handle case when the show local photos is not checked

**Steps to reproduce it**

Go to settings page. uncheck show local photos. Navigate to gallery page and press more images icon on top.

**LogCat for the issue**
 java.lang.IndexOutOfBoundsException: Invalid index 21, size is 0
                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                     at java.util.ArrayList.add(ArrayList.java:147)
                                                                     at vn.mbm.phimp.me.newGallery$PhotosAdapter.updateImageList(newGallery.java:3571)
                                                                     at vn.mbm.phimp.me.newGallery.resumeLocalPhoto(newGallery.java:3759)
                                                                     at vn.mbm.phimp.me.newGallery.onOptionsItemSelected(newGallery.java:487)
                                                                     at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2212)
                                                                     at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2295)
                                                                     at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
                                                                     at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
                                                                     
**Would you like to work on the issue?**

Yes.

**Comment by pa1pal** [comment]
The issue is already open #216
