### ISSUE TITLE
Connect to us on facebook crashes

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#2868]
**Describe the bug**
On clicking connect to us on facebook, the app crashes

**To Reproduce**

1. Go to 'About'
2. Click on 'Connect to facebook' at the bottom
3. crash

**Expected behavior**

Should not crash

**Logs**
```
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=fb://facewebmodal/f?href=https://www.facebook.com/phimpmeapp }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.Activity.startActivityForResult(Activity.java:4762)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:4691)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:5081)
        at android.app.Activity.startActivity(Activity.java:5049)
        at org.fossasia.phimpme.gallery.activities.AboutActivity$10.onClick(AboutActivity.java:229)
        at android.view.View.performClick(View.java:6710)
        at android.view.View.performClickInternal(View.java:6668)
        at android.view.View.access$3400(View.java:797)
        at android.view.View$PerformClick.run(View.java:26448)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by prudhvir3ddy** [comment]
@codedsun working fine for me. can you please explain in what situation it's crashing?
