### ISSUE TITLE
Crash in Edit Images

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/phimpme-android#294]
**Actual Behaviour**

I was editing an image. Editing as in I was applying a filter and cropped the image and saved it. Then I clicked on the image and chose to edit again. I cropped the image a little bit more and saved and the app crashed. It happened many times to me; so reporting as a bug!

**Expected Behaviour**

App should not crash. The image edited should be saved!

**Steps to reproduce it**

1. Open app
2. Click on an image and get the big image view
3. Click on the FAB and select _Edit_ button to open edit view
4. Apply a filter and crop the image
5. Click save
6. From the gallery, select the saved edited image
7. Get the image to editing view again
8. Crop the image again
9. Click _Save_

**LogCat for the issue**

> 04-02 19:59:57.324 20031-20031/vn.mbm.phimp.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@41c07098
                                                                     at android.graphics.Canvas.throwIfRecycled(Canvas.java:1026)
                                                                     at android.graphics.Canvas.drawBitmap(Canvas.java:1127)
                                                                     at vn.mbm.phimp.me.image.CropImage.onSaveClicked(CropImage.java:772)
                                                                     at vn.mbm.phimp.me.image.CropImage.access$1100(CropImage.java:69)
                                                                     at vn.mbm.phimp.me.image.CropImage$14.onClick(CropImage.java:496)
                                                                     at android.view.View.performClick(View.java:4439)
                                                                     at android.widget.Button.performClick(Button.java:139)
                                                                     at android.view.View$PerformClick.run(View.java:18395)
                                                                     at android.os.Handler.handleCallback(Handler.java:725)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                     at android.os.Looper.loop(Looper.java:176)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5317)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Screenshots of the issue**

> Not Available

**Would you like to work on the issue?**

I would like to give it a try!

**Comment by Abhi2424shek** [comment]
Sure @CloudyPadmal
