### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by minukag** [fossasia/phimpme-android#2945]
App crashing when clicking the pinterest accounts in accounts page
![Screenshot_20191219-152117_One UI Home](https://user-images.githubusercontent.com/57785026/71163961-21646600-2274-11ea-9048-d6e291844249.jpg)

**To Reproduce**
Click the PINTERESET button in Accounts tab.

**Smartphone Info:**
Samsung Galaxy A20 (2019)
Android 9 Pie OneUI 1.1

Anyone, please fix this issue.

**Comment by Hry789** [comment]
The Phimp.me need a large storage to run,so I suggest that we could save while we reached a certain time (like autosave?)

**Comment by sonusourav** [comment]
Here are the logs.

```
2020-01-11 19:35:10.298 27018-27018/org.fossasia.phimpme E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.phimpme, PID: 27018
    java.lang.IllegalStateException: No app responding to the Intent, please check the manifest to make sure the intent filter is set up properly.
        at com.pinterest.android.pdk.PDKClient.checkAppNumber(PDKClient.java:175)
        at com.pinterest.android.pdk.PDKClient.login(PDKClient.java:558)
        at com.pinterest.android.pdk.PDKClient.login(PDKClient.java:186)
        at org.fossasia.phimpme.accounts.AccountActivity.signInPinterest(AccountActivity.java:294)
        at org.fossasia.phimpme.accounts.AccountActivity.onItemClick(AccountActivity.java:193)
        at org.fossasia.phimpme.base.RecyclerItemClickListner$GestureListener.onSingleTapUp(RecyclerItemClickListner.java:68)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
        at org.fossasia.phimpme.base.RecyclerItemClickListner.onInterceptTouchEvent(RecyclerItemClickListner.java:30)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2962)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3090)
        at android.view.View.dispatchTouchEvent(View.java:10039)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3194)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
        at android.view.View.dispatchPointerEvent(View.java:10261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4503)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4368)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4054)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4111)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3961)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3927)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3935)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3908)
```
