### ISSUE TITLE
Crash on application start

### ISSUE THREAD

**Issue by TBog** [fossasia/phimpme-android#2982]
**Describe the bug**
I forked [phimpme-android](https://github.com/fossasia/phimpme-android) development branch to fix it because on my device it crashes on startup. The fix was migrating to iconics 4.0.2
The migrated app can be found here: [phimpme fork](https://github.com/TBog/phimpme-android/commits/tbog/iconics)
Now it still crashes on app start-up inside `gallery\data\providers\MediaStoreProvider.java` in method 
`public static ArrayList<Album> getAlbums(Context context)`

**To Reproduce**
Upon app start the app closes instantly.
Seems like the query has changed and the GROUP BY 'hack' used is not longer working.

**Logs**
```
2020-01-17 10:13:30.096 9755-10705/? E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteException: near "GROUP": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT parent, bucket_display_name FROM files WHERE ((_data>'') AND (owner_package_name IN ( 'org.fossasia.phimpme' ) OR media_type=2 OR media_type=4 OR media_type=0 AND mime_type LIKE 'audio/%' OR media_type=3 OR media_type=0 AND mime_type LIKE 'video/%' OR media_type=1 OR media_type=0 AND mime_type LIKE 'image/%') AND (is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND ((media_type=? ) GROUP BY ( parent ))
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1364)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:803)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1959)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:604)
        at com.android.providers.media.MediaProvider.queryInternal(MediaProvider.java:2167)
        at com.android.providers.media.MediaProvider.query(MediaProvider.java:1978)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Samsung Galaxy S10 plus |
|Android Version| Android version 10    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by TBog** [comment]
duplicate of #2927
