### ISSUE TITLE
Crashes on launch on Android Q

### ISSUE THREAD

**Issue by joshbowyer** [fossasia/phimpme-android#3043]
Downloaded from Google Play, tap the app icon to launch it, immediately crashes.

Phone: Oneplus 7 Pro
OS: LineageOS 17.1
Appver: 1.10.0.13

**Comment by barudaret** [comment]
I'm on a stock galaxy s20 and same problem

**Comment by nileshteji** [comment]
@joshbowyer can you tell us more about the crash or share the logcat result with us. It would be very helpful Thankyou.

**Comment by iamsdas** [comment]
Although the first launch took a while, It **opens** fine for me.
Phone: Realme 3 pro
OS: Pixel Experience 10 (Android Q)
App version: 1.11.0

**Comment by anaskaejdar** [comment]
There was an Android update and it no longer crashes for me.

**Comment by shatanikmahanty** [comment]
First Launch takes too much time on Samsung Galaxy A30s (Android Q).

The app is loading albums and images in splash screen through async tasks. And thus gets stuck at splash screen, a progress indicator can send proper signal to user that app is loading data. Current implementation gives user the feeling as if the app is lagging

Logcat : 

```
2021-02-01 23:46:36.196 4366-4366/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2021-02-01 23:46:36.197 4366-4366/? E/Zygote: accessInfo : 1
2021-02-01 23:46:36.202 4366-4366/? I/ossasia.phimpm: Late-enabling -Xcheck:jni
2021-02-01 23:46:36.240 4366-4366/? E/ossasia.phimpm: Unknown bits set in runtime_flags: 0x8000
2021-02-01 23:46:36.295 4366-4366/? D/ActivityThread: setConscryptValidator
2021-02-01 23:46:36.295 4366-4366/org.fossasia.phimpme D/ActivityThread: setConscryptValidator - put
2021-02-01 23:46:37.604 4366-4366/org.fossasia.phimpme I/MultiDex: VM with version 2.1.0 has multidex support
2021-02-01 23:46:37.604 4366-4366/org.fossasia.phimpme I/MultiDex: Installing application
2021-02-01 23:46:37.604 4366-4366/org.fossasia.phimpme I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2021-02-01 23:46:37.880 4366-4366/org.fossasia.phimpme D/PhoneWindow: forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4238 com.android.internal.policy.DecorView.updateColorViews:1491 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3216 android.view.Window.setFlags:1148 com.android.internal.policy.PhoneWindow.generateLayout:2444 
2021-02-01 23:46:37.881 4366-4366/org.fossasia.phimpme I/MultiWindowDecorSupport: updateCaptionType >> DecorView@29330a3[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2021-02-01 23:46:37.881 4366-4366/org.fossasia.phimpme D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@29330a3[]
2021-02-01 23:46:37.919 4366-4366/org.fossasia.phimpme W/ossasia.phimpm: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-02-01 23:46:37.920 4366-4366/org.fossasia.phimpme W/ossasia.phimpm: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-02-01 23:46:38.222 4366-4366/org.fossasia.phimpme D/ScrollView: initGoToTop
2021-02-01 23:46:38.278 4366-4366/org.fossasia.phimpme E/Android-Iconics: Can't init: com.mikepenz.iconics.typeface.library.ionicons.Ionicons
2021-02-01 23:46:38.315 4366-4366/org.fossasia.phimpme E/Android-Iconics: Can't init: com.mikepenz.iconics.typeface.library.fontawesome.FontAwesome
2021-02-01 23:46:38.343 4366-4366/org.fossasia.phimpme E/Iconics: Wrong icon name: faw_low_vision
2021-02-01 23:46:38.357 4366-4366/org.fossasia.phimpme E/Iconics: Wrong icon name: faw_trash_o
2021-02-01 23:46:38.387 4366-4366/org.fossasia.phimpme D/PhoneWindow: forceLight changed to false [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4244 com.android.internal.policy.PhoneWindow.setNavigationBarColor:4066 org.fossasia.phimpme.gallery.activities.SplashScreen.setStatusBarColor:159 org.fossasia.phimpme.base.ThemedActivity.onCreate:44 org.fossasia.phimpme.base.SharedMediaActivity.onCreate:12 
2021-02-01 23:46:38.505 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: setView = com.android.internal.policy.DecorView@29330a3 TM=true MM=false
2021-02-01 23:46:38.596 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: Relayout returned: old=(0,0,720,1560) new=(0,0,720,1560) req=(720,1560)0 dur=23 res=0x7 s={true 540125904896} ch=true
2021-02-01 23:46:38.598 4366-4702/org.fossasia.phimpme D/OpenGLRenderer: createReliableSurface : 0x7e53224480, 0x7dc2034000
2021-02-01 23:46:38.643 4366-4702/org.fossasia.phimpme D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2021-02-01 23:46:38.673 4366-4702/org.fossasia.phimpme W/Gralloc3: mapper 3.x is not supported
2021-02-01 23:46:38.680 4366-4702/org.fossasia.phimpme I/gralloc: Arm Module v1.0
2021-02-01 23:46:38.744 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: MSG_RESIZED: frame=(0,0,720,1560) ci=(0,53,0,84) vi=(0,53,0,84) or=1
2021-02-01 23:46:40.582 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: stopped(false) old=false
2021-02-01 23:46:40.590 4366-4959/org.fossasia.phimpme W/System.err: java.io.FileNotFoundException: /data/user/0/org.fossasia.phimpme/cache/albums.dat: open failed: ENOENT (No such file or directory)
2021-02-01 23:46:40.597 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
2021-02-01 23:46:40.597 4366-4959/org.fossasia.phimpme W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:159)
2021-02-01 23:46:40.598 4366-4959/org.fossasia.phimpme W/System.err:     at org.fossasia.phimpme.gallery.data.HandlingAlbums.restoreBackup(HandlingAlbums.java:146)
2021-02-01 23:46:40.598 4366-4959/org.fossasia.phimpme W/System.err:     at org.fossasia.phimpme.gallery.activities.SplashScreen$PrefetchAlbumsData.doInBackground(SplashScreen.java:221)
2021-02-01 23:46:40.598 4366-4959/org.fossasia.phimpme W/System.err:     at org.fossasia.phimpme.gallery.activities.SplashScreen$PrefetchAlbumsData.doInBackground(SplashScreen.java:217)
2021-02-01 23:46:40.599 4366-4959/org.fossasia.phimpme W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2021-02-01 23:46:40.599 4366-4959/org.fossasia.phimpme W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-02-01 23:46:40.599 4366-4959/org.fossasia.phimpme W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2021-02-01 23:46:40.600 4366-4959/org.fossasia.phimpme W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-02-01 23:46:40.600 4366-4959/org.fossasia.phimpme W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-02-01 23:46:40.600 4366-4959/org.fossasia.phimpme W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-02-01 23:46:40.601 4366-4959/org.fossasia.phimpme W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
2021-02-01 23:46:40.602 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.Linux.open(Native Method)
2021-02-01 23:46:40.602 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-02-01 23:46:40.602 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
2021-02-01 23:46:40.602 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-02-01 23:46:40.603 4366-4959/org.fossasia.phimpme W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7825)
2021-02-01 23:46:40.603 4366-4959/org.fossasia.phimpme W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
2021-02-01 23:46:40.603 4366-4959/org.fossasia.phimpme W/System.err: 	... 10 more
2021-02-01 23:46:40.619 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: Relayout returned: old=(0,0,720,1560) new=(0,0,720,1560) req=(720,1560)0 dur=14 res=0x1 s={true 540125904896} ch=false
2021-02-01 23:46:40.621 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: MSG_WINDOW_FOCUS_CHANGED 1 1
2021-02-01 23:46:40.621 4366-4366/org.fossasia.phimpme D/InputMethodManager: prepareNavigationBarInfo() DecorView@29330a3[SplashScreen]
2021-02-01 23:46:40.621 4366-4366/org.fossasia.phimpme D/InputMethodManager: getNavigationBarColor() 1174405120
2021-02-01 23:46:40.624 4366-4366/org.fossasia.phimpme D/InputMethodManager: prepareNavigationBarInfo() DecorView@29330a3[SplashScreen]
2021-02-01 23:46:40.624 4366-4366/org.fossasia.phimpme D/InputMethodManager: getNavigationBarColor() 1174405120
2021-02-01 23:46:40.624 4366-4366/org.fossasia.phimpme V/InputMethodManager: Starting input: tba=org.fossasia.phimpme ic=null mNaviBarColor 1174405120 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2021-02-01 23:46:40.624 4366-4366/org.fossasia.phimpme D/InputMethodManager: startInputInner - Id : 0
2021-02-01 23:46:40.624 4366-4366/org.fossasia.phimpme I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-02-01 23:46:40.641 4366-4366/org.fossasia.phimpme D/InputMethodManager: prepareNavigationBarInfo() DecorView@29330a3[SplashScreen]
2021-02-01 23:46:40.641 4366-4366/org.fossasia.phimpme D/InputMethodManager: getNavigationBarColor() 1174405120
2021-02-01 23:46:40.641 4366-4366/org.fossasia.phimpme V/InputMethodManager: Starting input: tba=org.fossasia.phimpme ic=null mNaviBarColor 1174405120 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2021-02-01 23:46:40.641 4366-4366/org.fossasia.phimpme D/InputMethodManager: startInputInner - Id : 0
2021-02-01 23:46:41.234 4366-4366/org.fossasia.phimpme D/splashscreen: Gif animation completed
2021-02-01 23:47:22.109 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: ViewPostIme pointer 0
2021-02-01 23:47:22.299 4366-4366/org.fossasia.phimpme D/ViewRootImpl@f331c05[SplashScreen]: ViewPostIme pointer 1
```
