### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iamvs-2002** [fossasia/phimpme-android#3123]
**Describe the bug**
App crashes on startup.

**To Reproduce**

**Expected behavior**

**Logs**

2020-11-26 14:04:14.829 5500-5500/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.phimpme, PID: 5500
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/lib/x86, /data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/lib/x86, /data/app/~~_4gEh7OMbn7abZQmOWJreA==/org.fossasia.phimpme-HHZPlBDPZ_9Ium3eMmP9MQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7228)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-11-26 14:04:38.048 1699-5530/com.google.android.gms E/ConfigFileUtils: Failed to read config file: /data/user_de/0/com.google.android.gms/app_chimera/next_container.pb: open failed: ENOENT (No such file or directory)
2020-11-26 14:04:44.826 518-648/system_process E/ClipboardService: Denying clipboard access to org.chromium.webview_shell, application is not in focus nor is it a system service for user 0
2020-11-26 14:04:56.926 518-648/system_process E/ClipboardService: Denying clipboard access to org.chromium.webview_shell, application is not in focus nor is it a system service for user 0
2020-11-26 14:07:29.163 204-206/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2020-11-26 14:07:29.171 204-206/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied

**Screenshots**

![Screenshot (39)](https://user-images.githubusercontent.com/54304786/100327653-92b6a800-2ff1-11eb-80c4-17394d9f16c4.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device      Google Pixel XL   ||
|Android Version      API 30, Android 11.0 (R)|    |

**Additional context**

**Would you like to work on the issue?**
I need help in understanding the issue.

- [ ] Yes
- [x] No
- Other:

**Comment by kavinprabhuc** [comment]
It's exactly the same for me too! Not able to sort it out the cause of it!

**Comment by asaikarthikeya** [comment]
@kavinprabhuc  Did you find some way?

**Comment by indexoutofboundsexceptionn** [comment]
I am also facing the same issue.

**Comment by kavinprabhuc** [comment]
@asaikarthikeya I was not able to do anything with this one. While I was searching for image editor lib I ended up finding https://github.com/iamutkarshtiwari/Ananas which has mostly what I was looking for. So dropping this one here!

**Comment by asaikarthikeya** [comment]
> I am also facing the same issue.

Mentors are not looking at this project right now.

**Comment by Varinder-KM** [comment]
Hey! May I look into this issue?

**Comment by asaikarthikeya** [comment]
@Varinder-KM Ya definitely you can . Go ahead :)
