### ISSUE TITLE
Failed to Build Project

### ISSUE THREAD

**Issue by RAJATNEGI** [fossasia/phimpme-android#3195]
**Describe the bug**
Build failed to build Successfully

**To Reproduce**

1. Clone repo
2.Try to build on Android studio
3. Result: Project failed to build

**Expected behavior**
Build should be successfully build. 

**Logs**
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.phimpme, PID: 6746
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/base.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/lib/arm64, /data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7318)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6778)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6628)
        at android.app.ActivityThread.access$1700(ActivityThread.java:232)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/base.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/lib/arm64, /data/app/org.fossasia.phimpme-kkaMumd2mnSoQ92VlK5Suw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7278)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6778) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6628) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:232) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/30105033/132647511-a7020470-3229-4d43-b70b-05d6e03f13f3.PNG)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**
I like to work on this issue
- [1 ] Yes
- [ ] No
- Other:

**Comment by RAJATNEGI** [comment]
@abishekvashok  can i work on this issue
