### ISSUE TITLE
App crashing on pressing back after selecting map or settings.

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/phimpme-android#320]
**Actual Behaviour**
Currently, App is crashing after selecting any option other than the gallery and then pressing back button.

**Expected Behaviour**
App should gracefully exit with alertDialog or should take the user to the previously selected screen.

**Steps to reproduce it**

1. Select any option from bottom navigation other than gallery.
2. Press back button.
3. App crashes.

**LogCat for the issue**

`
04-07 11:57:12.873 18900-18900/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: vn.mbm.phimp.me, PID: 18900
                                                   java.lang.ClassCastException: vn.mbm.phimp.me.Settings cannot be cast to vn.mbm.phimp.me.newGallery
                                                       at vn.mbm.phimp.me.PhimpMe.onKeyDown(PhimpMe.java:791)
                                                       at android.view.KeyEvent.dispatch(KeyEvent.java:2707)
                                                       at android.app.Activity.dispatchKeyEvent(Activity.java:2784)
                                                       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:547)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
                                                       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:315)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2402)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4659)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4615)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4137)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4137)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4326)
                                                       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4496)
                                                       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
                                                       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
                                                       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
                                                       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
                                                       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:328)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-07 11:59:39.227 20078-20078/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: vn.mbm.phimp.me, PID: 20078
                                                   java.lang.ClassCastException: vn.mbm.phimp.me.Camera2 cannot be cast to vn.mbm.phimp.me.newGallery
                                                       at vn.mbm.phimp.me.PhimpMe.onKeyDown(PhimpMe.java:791)
                                                       at android.view.KeyEvent.dispatch(KeyEvent.java:2707)
                                                       at android.app.Activity.dispatchKeyEvent(Activity.java:2784)
                                                       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:547)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
                                                       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:315)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:57)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2402)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4659)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4615)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4137)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4137)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4110)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4163)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4129)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4326)
                                                       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4496)
                                                       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
                                                       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
                                                       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
                                                       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
                                                       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:328)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                   
                                                   
`

**Would you like to work on the issue?**

Yes

**Comment by amitiwary999** [comment]
@saurabhjn76 I solved this issue . This issue is generated due to my previous PR. Can I send PR for this?

**Comment by saurabhjn76** [comment]
Sure go on!!
