### ISSUE TITLE
App crashes if user edit image in upload section

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/phimpme-android#321]
**Actual Behaviour**

App crashes if user edit image in upload section

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Add image in upload section and then click on it. Image edit activity will open. Now rotate image image by clicking on rotate button and then apply some filter.

**LogCat for the issue**

java.lang.IllegalStateException: Can't copy a recycled bitmap
                      at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)
                      at android.graphics.Bitmap.copy(Bitmap.java:561)
                      at vn.mbm.phimp.me.ImagesFilter.convertToPolaroid(ImagesFilter.java:134)
                      at vn.mbm.phimp.me.gallery3d.media.CropImage$11.onClick(CropImage.java:669)
                      at android.view.View.performClick(View.java:4757)
                      at android.view.View$PerformClick.run(View.java:19757)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5233)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
OK please go on..
