### ISSUE TITLE
App crashes when camera button on bottomnavigationbar is pressed

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#421]
**Actual Behaviour**

App crashes when camera button on bottomnavigationbar is pressed. 

**Expected Behaviour**

No crash should occur

**Steps to reproduce it**

Open app, press camera button on bottom navigation bar

**LogCat for the issue**

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 18791
                                                                 java.lang.RuntimeException: setParameters failed
                                                                     at android.hardware.Camera.native_setParameters(Native Method)
                                                                     at android.hardware.Camera.setParameters(Camera.java:1888)
                                                                     at vn.mbm.phimp.me.Camera2$7.onItemSelected(Camera2.java:495)
                                                                     at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
                                                                     at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
                                                                     at android.widget.AdapterView.-wrap1(AdapterView.java)
                                                                     at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:890)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Would you like to work on the issue?**

yes

**Comment by vinaysajjanapu** [comment]
Code cleaned
