### ISSUE TITLE
App crash on open camera. 

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#517]
**Actual Behaviour**

App crashed on opening camera from bottom navigation View.

**Expected Behaviour**

It should not crash, open camera instead.

**Steps to reproduce it**

Open camera from Bottom Navigation View.

**LogCat for the issue**

`FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 12051
                                                                 java.lang.NullPointerException
                                                                     at vn.mbm.phimp.me.opencamera.Camera.TinyDB.checkForNullValue(TinyDB.java:565)
                                                                     at vn.mbm.phimp.me.opencamera.Camera.TinyDB.putString(TinyDB.java:411)
                                                                     at vn.mbm.phimp.me.opencamera.Camera.CameraActivity.getSettingDetail(CameraActivity.java:993)
                                                                     at vn.mbm.phimp.me.opencamera.Camera.CameraActivity.onWindowFocusChanged(CameraActivity.java:742)
                                                                     at android.support.v7.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:128)
                                                                     at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1467)
                                                                     at android.view.View.dispatchWindowFocusChanged(View.java:10258)
                                                                     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1193)
                                                                     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3605)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by mohitmanuja** [comment]
@pa1pal Okay, I will see this.
