### ISSUE TITLE
On click add image : Unfortunately Phimp.me has stopped

### ISSUE THREAD

**Issue by optnio00** [fossasia/phimpme-android#66]
When i want to add imagw for edit or upload. App has been stopped

**Comment by optnio00** [comment]
yes i have 

`03-03 17:23:56.120 22535-22535/vn.mbm.phimp.me V/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
03-03 17:23:56.125 22535-22535/vn.mbm.phimp.me D/AndroidRuntime: Shutting down VM
03-03 17:23:56.128 22535-22535/vn.mbm.phimp.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 22535
                                                                 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                                     at vn.mbm.phimp.me.gallery.PhimpMeGallery.onClick(PhimpMeGallery.java:215)
                                                                     at android.view.View.performClick(View.java:4802)
                                                                     at android.view.View$PerformClick.run(View.java:20101)
                                                                     at android.os.Handler.handleCallback(Handler.java:810)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:189)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5530)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)`

**Comment by Abhi2424shek** [comment]
Index out of bound exception! Somethjng is trying to access a value beyond that is in a cloumn beyond the length of an array

**Comment by anantprsd5** [comment]
@optnio00 I am not getting any such crashes. Are you getting this frequently?

**Comment by Abhi2424shek** [comment]
Do you open settings?

**Comment by optnio00** [comment]
@anantprsd5  are you try to upload any image of large scale size.
@Abhi2424shek  this problem not in settings. this problrm held in gallery , when upload large scale size image

**Comment by optnio00** [comment]
but now i resolved this issue. Now i am able to upload an image of more than 1028*1028px size

**Comment by Abhi2424shek** [comment]
Then send the PR pls

**Comment by Abhi2424shek** [comment]
Is the issue still there?

**Comment by Abhi2424shek** [comment]
@optnio00 are you on it?

**Comment by Abhi2424shek** [comment]
It's working now
