### ISSUE TITLE
App crashes while trying to switch camera

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#69]
**Actual Behaviour**

Currently when the user tries to switch the camera, there is always an app crash as Camera API is depreciated

**Expected Behaviour**

There should be no such crashes and depreciated code should be changed with new cameraV2 api.

**Steps to reproduce it**

Open app , go to camera , press the camera switch button.

**Would you like to work on the issue?**

Yes.

**Comment by dynamitechetan** [comment]
on my phone its working perfectly 
Any logs?

**Comment by anantprsd5** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 12855
                                                                 java.lang.RuntimeException: setParameters failed
                                                                     at android.hardware.Camera.native_setParameters(Native Method)
                                                                     at android.hardware.Camera.setParameters(Camera.java:2173)
                                                                     at vn.mbm.phimp.me.Preview.switchCamera(Camera2.java:597)
                                                                     at vn.mbm.phimp.me.Camera2$4.onClick(Camera2.java:221)
                                                                     at android.view.View.performClick(View.java:5226)
                                                                     at android.view.View$PerformClick.run(View.java:21350)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5582)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616
```

**Comment by anantprsd5** [comment]
@Abhi2424shek @pa1pal Can you please check if the app is crashing on camera switch in your device because for me its crashing but for @dynamitechetan its working perfectly. If the crash is there, I will start working on it.

**Comment by pa1pal** [comment]
@anantprsd5 it's not crashing in mine. But if this in your case. So you can fix it.

**Comment by Abhi2424shek** [comment]
I am not too getting a crash! Can you check your apk version. @anantprsd5

**Comment by anantprsd5** [comment]
@Abhi2424shek I'm using version 1.5, the latest codes from the development branch. The problem is with my phone only I guess. I checked with another phones, It's working fine in them.

**Comment by Narutuffy** [comment]
@anantprsd5  It is not just your phone, I am facing the same problem with my phone too.

**Comment by anantprsd5** [comment]
@Narutuffy Yeah. I am working on it.

**Comment by Abhi2424shek** [comment]
I am using MUI, what all are you all using, who is your manufacturer @anantprsd5 @Narutuffy

**Comment by anantprsd5** [comment]
@Abhi2424shek I am using le2 with EUI.

**Comment by Narutuffy** [comment]
I'm using Moto G Gen1, near stock-android.

**Comment by Narutuffy** [comment]
The problem is there when you try to switch the camera twice. Here's the log
```

03-04 23:39:28.128 13755-13755/vn.mbm.phimp.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 13755
                                                                 java.lang.RuntimeException: setParameters failed
                                                                     at android.hardware.Camera.native_setParameters(Native Method)
                                                                     at android.hardware.Camera.setParameters(Camera.java:2015)
                                                                     at vn.mbm.phimp.me.Preview.switchCamera(Camera2.java:597)
                                                                     at vn.mbm.phimp.me.Camera2$4.onClick(Camera2.java:237)
                                                                     at android.view.View.performClick(View.java:4785)
                                                                     at android.view.View$PerformClick.run(View.java:19884)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
```

**Comment by dynamitechetan** [comment]
```
	for (Camera.Size size : parameters.getSupportedPictureSizes()) {
			if (1600 <= size.width & size.width <= 1920) {
				parameters.setPreviewSize(size.width, size.height);
				parameters.setPictureSize(size.width, size.height);
				break;
			}
		}
```
Comment the above and replace it with code below. Then test the same issue.
```
		List<Camera.Size> sizes = parameters.getSupportedPreviewSizes();
		Camera.Size cs = sizes.get(0);
		parameters.setPreviewSize(cs.width, cs.height);
		parameters.setPictureSize(cs.width, cs.height);

```

**Comment by anantprsd5** [comment]
@dynamitechetan Yeah, its working fine with the above code.

**Comment by dynamitechetan** [comment]
Can I send a PR?

**Comment by anantprsd5** [comment]
@dynamitechetan Sure. Thanks. :)

**Comment by dynamitechetan** [comment]
@anantprsd5  if you comment all the code above requestLayout() method does it crash?

**Comment by anantprsd5** [comment]
@dynamitechetan If we comment all the code above requestLayout() then we have to remove the line which is setting the parameters and if we remove that it is working fine. I don't understand one thing is that with the present code also the size.width gives a value of 1920 and with the above code also the cs.width returns same value of 1920. So why is it crashing with the present code.

**Comment by dynamitechetan** [comment]
okay.
