### ISSUE TITLE
Opening another image after the previous image has been closed crashes the app

### ISSUE THREAD

**Issue by Narutuffy** [fossasia/phimpme-android#75]
**Actual Behaviour**

Open the image, press back button and opening another image crashes the app

**Expected Behaviour**

The app shouldn't crash after opening another image

**Steps to reproduce it**
Open the image, press back button and open another image (Repeat it as the behavior appears to be random, sometimes the crash happens while opening second image, sometimes third)

**LogCat for the issue**
```
03-05 00:13:23.059 9470-9470/vn.mbm.phimp.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: vn.mbm.phimp.me, PID: 9470
                                                               java.lang.RuntimeException: Unable to resume activity {vn.mbm.phimp.me/vn.mbm.phimp.me.PhimpMe}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3028)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3063)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
                                                                   at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:64)
                                                                   at android.database.BulkCursorToCursorAdaptor.requery(BulkCursorToCursorAdaptor.java:133)
                                                                   at android.database.CursorWrapper.requery(CursorWrapper.java:186)
                                                                   at android.app.Activity.performRestart(Activity.java:6062)
                                                                   at android.app.Activity.performResume(Activity.java:6088)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3011)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3063) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
```

**Would you like to work on the issue?**

Yes

**Comment by anantprsd5** [comment]
@Narutuffy I am not facing any such issues.

**Comment by anantprsd5** [comment]
@Narutuffy Let others also test the same to check whether the issue persists in their devices also. You can fix this issue if it's the case with your device.

**Comment by Narutuffy** [comment]
@anantprsd5 Sure

**Comment by CloudyPadmal** [comment]
@Narutuffy are you building the apk using _development_ branch?

**Comment by Narutuffy** [comment]
I am yet to build apk using development branch, have tried from apk branch and also from the link provided
[link]( https://github.com/fossasia/phimpme-android/raw/apk/app-debug.apk)

**Comment by dynamitechetan** [comment]
that link is probably not updated. try to build it and then test.

**Comment by Narutuffy** [comment]
On it

**Comment by Narutuffy** [comment]
My mistake, working with the development branch
