### ISSUE TITLE
Excluding last album from photos mode crashes the application

### ISSUE THREAD

**Issue by vinaysajjanapu** [fossasia/phimpme-android#896]
**Actual Behaviour**

Excluding last album from photos mode crashes the application.

**Expected Behaviour**

The crash shouldn't occur.
The option shouldn't be there in photos mode or it should be renamed to "exclude album" instead of "exclude" because the user might confuse it with exclude specific photo.

**Steps to reproduce it**

In gallery page -> open last album -> long press image to select it -> in the context menu click exclude.

**LogCat for the issue**

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 22690
                                                                      java.lang.IndexOutOfBoundsException: Index: 13, Size: 12
                                                                          at java.util.ArrayList.get(ArrayList.java:411)
                                                                          at org.fossasia.phimpme.leafpic.data.HandlingAlbums.getCurrentAlbum(HandlingAlbums.java:85)
                                                                          at org.fossasia.phimpme.MyApplication.getAlbum(MyApplication.java:32)
                                                                          at org.fossasia.phimpme.base.SharedMediaActivity.getAlbum(SharedMediaActivity.java:24)
                                                                          at org.fossasia.phimpme.leafpic.activities.LFMainActivity.onPrepareOptionsMenu(LFMainActivity.java:877)

**Would you like to work on the issue?**

yes

@pa1pal @mohitmanuja @anantprsd5 @Subhankar29 
Should the option be removed or renamed or just the crash be fixed?

**Comment by anantprsd5** [comment]
@vinaysajjanapu I think that options should be removed from the Photos mode. It should only be there in the Albums mode(edit mode)
